/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

/**
 *
 * @author ACER
 */
public class AdminStaff extends javax.swing.JFrame {

    /**
     * Creates new form AdminStaff
     */
    public AdminStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnManageEnrollment = new javax.swing.JButton();
        btnManageCourseAndSubject = new javax.swing.JButton();
        btnManageFacultyAndSchedules = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageEnrollment.setText("🆕 Manage Student Enrollment");
        btnManageEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnrollmentActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 470, 40));

        btnManageCourseAndSubject.setText("📚 Manage Courses & Subjects");
        btnManageCourseAndSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseAndSubjectActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageCourseAndSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 470, 40));

        btnManageFacultyAndSchedules.setText("🧑‍🏫 Faculty & Class Schedules");
        btnManageFacultyAndSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyAndSchedulesActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageFacultyAndSchedules, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 470, 40));

        jButton4.setText("💰 Process Payments & Billing");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 470, 40));

        jButton5.setText("📊 Enrollment Reports ");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 470, 40));

        jButton6.setText("🖨 Generate Official Documents");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 470, 40));

        jButton7.setText("🔓 Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 470, 40));

        jButton9.setText("⚙️ System Settings");
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 470, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1320, 580));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BatStateU-NEU-Logo.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnManageEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnrollmentActionPerformed
        ManageStudentEnrollment manageEnrollment = new ManageStudentEnrollment();
        manageEnrollment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageEnrollmentActionPerformed

    private void btnManageCourseAndSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseAndSubjectActionPerformed
        ManageCourseAndSubject manageCourseAndSubject = new ManageCourseAndSubject();
        manageCourseAndSubject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageCourseAndSubjectActionPerformed

    private void btnManageFacultyAndSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyAndSchedulesActionPerformed
        ManageFacultyAndSchedules manageFacultyAndSchedules = new ManageFacultyAndSchedules();
        manageFacultyAndSchedules.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageFacultyAndSchedulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourseAndSubject;
    private javax.swing.JButton btnManageEnrollment;
    private javax.swing.JButton btnManageFacultyAndSchedules;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
